In [1]:
'''
References:

https://towardsdatascience.com/fantasy-premier-league-value-analysis-python-tutorial-using-the-fpl-api-8031edfe9910

https://www.game-change.co.uk/2023/02/10/a-complete-guide-to-the-fantasy-premier-league-fpl-api/

'''

'\nReferences:\n\nhttps://towardsdatascience.com/fantasy-premier-league-value-analysis-python-tutorial-using-the-fpl-api-8031edfe9910\n\nhttps://www.game-change.co.uk/2023/02/10/a-complete-guide-to-the-fantasy-premier-league-fpl-api/\n\n'

In [2]:
import requests
import pandas as pd
from datetime import date
pd.options.mode.chained_assignment = None

In [3]:
print('Data Last Pulled: {}'.format(date.today()))

Data Last Pulled: 2024-09-27

In [4]:
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
r = requests.get(url)
json = r.json()

In [5]:
url_fixtures = 'https://fantasy.premierleague.com/api/fixtures/'
r2 = requests.get(url_fixtures)
json2 = r2.json()

In [6]:
fixtures = pd.DataFrame(json2)

In [7]:
fixtures.head().T

,0,1,2,3,4
code,2444470,2444473,2444471,2444472,2444474
event,1,1,1,1,1
finished,True,True,True,True,True
finished_provisional,True,True,True,True,True
id,1,4,2,3,5
kickoff_time,2024-08-16T19:00:00Z,2024-08-17T11:30:00Z,2024-08-17T14:00:00Z,2024-08-17T14:00:00Z,2024-08-17T14:00:00Z
minutes,90,90,90,90,90
provisional_start_time,False,False,False,False,False
started,True,True,True,True,True
team_a,9,12,20,5,17
team_a_score,0.0,2.0,0.0,3.0,0.0
team_h,14,10,1,8,15
team_h_score,1.0,0.0,2.0,0.0,1.0
stats,"[{'identifier': 'goals_scored', 'a': [], 'h': ...","[{'identifier': 'goals_scored', 'a': [{'value'...","[{'identifier': 'goals_scored', 'a': [], 'h': ...","[{'identifier': 'goals_scored', 'a': [{'value'...","[{'identifier': 'goals_scored', 'a': [], 'h': ..."
team_h_difficulty,2,4,2,2,2
team_a_difficulty,3,2,5,3,4
pulse_id,115827,115830,115828,115829,115831

In [8]:
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [9]:
print(json2[0])

{'code': 2444470, 'event': 1, 'finished': True, 'finished_provisional': True, 'id': 1, 'kickoff_time': '2024-08-16T19:00:00Z', 'minutes': 90, 'provisional_start_time': False, 'started': True, 'team_a': 9, 'team_a_score': 0, 'team_h': 14, 'team_h_score': 1, 'stats': [{'identifier': 'goals_scored', 'a': [], 'h': [{'value': 1, 'element': 389}]}, {'identifier': 'assists', 'a': [], 'h': [{'value': 1, 'element': 372}]}, {'identifier': 'own_goals', 'a': [], 'h': []}, {'identifier': 'penalties_saved', 'a': [], 'h': []}, {'identifier': 'penalties_missed', 'a': [], 'h': []}, {'identifier': 'yellow_cards', 'a': [{'value': 1, 'element': 240}, {'value': 1, 'element': 241}, {'value': 1, 'element': 243}], 'h': [{'value': 1, 'element': 377}, {'value': 1, 'element': 382}]}, {'identifier': 'red_cards', 'a': [], 'h': []}, {'identifier': 'saves', 'a': [{'value': 4, 'element': 248}], 'h': [{'value': 2, 'element': 383}]}, {'identifier': 'bonus', 'a': [], 'h': [{'value': 3, 'element': 389}, {'value': 2, 'element': 594}, {'value': 1, 'element': 369}, {'value': 1, 'element': 380}]}, {'identifier': 'bps', 'a': [{'value': 16, 'element': 249}, {'value': 15, 'element': 240}, {'value': 15, 'element': 255}, {'value': 13, 'element': 245}, {'value': 12, 'element': 248}, {'value': 11, 'element': 19}, {'value': 10, 'element': 251}, {'value': 7, 'element': 257}, {'value': 5, 'element': 239}, {'value': 5, 'element': 241}, {'value': 5, 'element': 247}, {'value': 4, 'element': 254}, {'value': 4, 'element': 259}, {'value': 3, 'element': 252}, {'value': 2, 'element': 243}, {'value': 2, 'element': 256}], 'h': [{'value': 33, 'element': 389}, {'value': 32, 'element': 594}, {'value': 26, 'element': 369}, {'value': 26, 'element': 380}, {'value': 25, 'element': 383}, {'value': 22, 'element': 377}, {'value': 21, 'element': 378}, {'value': 19, 'element': 368}, {'value': 11, 'element': 364}, {'value': 11, 'element': 372}, {'value': 10, 'element': 366}, {'value': 5, 'element': 385}, {'value': 3, 'element': 381}, {'value': 3, 'element': 593}, {'value': 2, 'element': 371}, {'value': -1, 'element': 382}]}], 'team_h_difficulty': 2, 'team_a_difficulty': 3, 'pulse_id': 115827}

In [10]:
print(json2[9])

{'code': 2444479, 'event': 1, 'finished': True, 'finished_provisional': True, 'id': 10, 'kickoff_time': '2024-08-19T19:00:00Z', 'minutes': 90, 'provisional_start_time': False, 'started': True, 'team_a': 18, 'team_a_score': 1, 'team_h': 11, 'team_h_score': 1, 'stats': [{'identifier': 'goals_scored', 'a': [{'value': 1, 'element': 495}], 'h': [{'value': 1, 'element': 306}]}, {'identifier': 'assists', 'a': [{'value': 1, 'element': 494}], 'h': [{'value': 1, 'element': 570}]}, {'identifier': 'own_goals', 'a': [], 'h': []}, {'identifier': 'penalties_saved', 'a': [], 'h': []}, {'identifier': 'penalties_missed', 'a': [], 'h': []}, {'identifier': 'yellow_cards', 'a': [{'value': 1, 'element': 480}], 'h': [{'value': 1, 'element': 291}]}, {'identifier': 'red_cards', 'a': [], 'h': []}, {'identifier': 'saves', 'a': [{'value': 2, 'element': 508}], 'h': [{'value': 5, 'element': 293}]}, {'identifier': 'bonus', 'a': [{'value': 1, 'element': 495}], 'h': [{'value': 3, 'element': 570}, {'value': 2, 'element': 306}]}, {'identifier': 'bps', 'a': [{'value': 28, 'element': 495}, {'value': 25, 'element': 494}, {'value': 18, 'element': 503}, {'value': 17, 'element': 82}, {'value': 16, 'element': 508}, {'value': 15, 'element': 480}, {'value': 13, 'element': 498}, {'value': 12, 'element': 499}, {'value': 12, 'element': 506}, {'value': 9, 'element': 481}, {'value': 8, 'element': 491}, {'value': 3, 'element': 504}, {'value': 3, 'element': 509}, {'value': 2, 'element': 505}, {'value': 1, 'element': 489}, {'value': -1, 'element': 497}], 'h': [{'value': 37, 'element': 570}, {'value': 33, 'element': 306}, {'value': 17, 'element': 309}, {'value': 15, 'element': 293}, {'value': 15, 'element': 295}, {'value': 14, 'element': 300}, {'value': 13, 'element': 117}, {'value': 9, 'element': 296}, {'value': 7, 'element': 291}, {'value': 6, 'element': 307}, {'value': 4, 'element': 298}, {'value': 3, 'element': 285}, {'value': 3, 'element': 299}, {'value': 2, 'element': 290}]}], 'team_h_difficulty': 3, 'team_a_difficulty': 2, 'pulse_id': 115836}

In [11]:
json2[0].keys()

dict_keys(['code', 'event', 'finished', 'finished_provisional', 'id', 'kickoff_time', 'minutes', 'provisional_start_time', 'started', 'team_a', 'team_a_score', 'team_h', 'team_h_score', 'stats', 'team_h_difficulty', 'team_a_difficulty', 'pulse_id'])

In [12]:
'''
events = gameweeks, in FPL
game_settings = fpl game settings
phases = months, and which game days they cover
teams = as titled
total_players = # of total fpl managers this season
elements = players in the premier league
element_stats = metadata of certain player statistics i.e. minutes = Minutes played
element_types = information about different player positions (midfield, goalie)
'''

'\nevents = gameweeks, in FPL\ngame_settings = fpl game settings\nphases = months, and which game days they cover\nteams = as titled\ntotal_players = # of total fpl managers this season\nelements = players in the premier league\nelement_stats = metadata of certain player statistics i.e. minutes = Minutes played\nelement_types = information about different player positions (midfield, goalie)\n'

In [13]:
players = pd.DataFrame(json['elements'])
player_types = pd.DataFrame(json['element_types'])
teams = pd.DataFrame(json['teams'])
events = pd.DataFrame(json['events'])
#element_stats = pd.DataFrame(json['element_stats'])
#phases = pd.DataFrame(json['phases'])

fixtures = pd.DataFrame(json2)

In [14]:
teams.head().T

                             0            1            2          3         4
code                         3            7           91         94        36
draw                         0            0            0          0         0
form                      None         None         None       None      None
id                           1            2            3          4         5
loss                         0            0            0          0         0
name                   Arsenal  Aston Villa  Bournemouth  Brentford  Brighton
played                       0            0            0          0         0
points                       0            0            0          0         0
position                     0            0            0          0         0
short_name                 ARS          AVL          BOU        BRE       BHA
strength                     5            3            3          3         3
team_division             None         None         None       None      None
unavailable              False        False        False      False     False
win                          0            0            0          0         0
strength_overall_home     1350         1120         1100       1100      1100
strength_overall_away     1380         1245         1100       1100      1100
strength_attack_home      1370         1110         1075       1105      1100
strength_attack_away      1370         1140         1100       1095      1105
strength_defence_home     1330         1130         1130       1100      1100
strength_defence_away     1390         1350         1105       1110      1100
pulse_id                     1            2          127        130       131

In [15]:
events.columns

Index(['id', 'name', 'deadline_time', 'release_time', 'average_entry_score',
       'finished', 'data_checked', 'highest_scoring_entry',
       'deadline_time_epoch', 'deadline_time_game_offset', 'highest_score',
       'is_previous', 'is_current', 'is_next', 'cup_leagues_created',
       'h2h_ko_matches_created', 'ranked_count', 'chip_plays', 'most_selected',
       'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained'],
      dtype='object')

In [16]:
events.head().T

,0,1,2,3,4
id,1,2,3,4,5
name,Gameweek 1,Gameweek 2,Gameweek 3,Gameweek 4,Gameweek 5
deadline_time,2024-08-16T17:30:00Z,2024-08-24T10:00:00Z,2024-08-31T10:00:00Z,2024-09-14T10:00:00Z,2024-09-21T10:00:00Z
release_time,None,None,None,None,None
average_entry_score,57,69,64,51,58
finished,True,True,True,True,True
data_checked,True,True,True,True,True
highest_scoring_entry,3546234.0,9442126.0,430195.0,3560750.0,1773336.0
deadline_time_epoch,1723829400,1724493600,1725098400,1726308000,1726912800
deadline_time_game_offset,0,0,0,0,0
highest_score,127.0,154.0,130.0,120.0,131.0
is_previous,False,False,False,True,False
is_current,False,False,False,False,True
is_next,False,False,False,False,False
cup_leagues_created,False,True,True,True,True
h2h_ko_matches_created,False,True,True,True,True
ranked_count,8597356,9543353,9912161,10178753,10279610
chip_plays,"[{'chip_name': 'bboost', 'num_played': 144974}...","[{'chip_name': 'bboost', 'num_played': 118782}...","[{'chip_name': 'bboost', 'num_played': 87334},...","[{'chip_name': 'bboost', 'num_played': 83637},...","[{'chip_name': 'bboost', 'num_played': 66447},..."
most_selected,401.0,401.0,351.0,351.0,351.0
most_transferred_in,27.0,594.0,177.0,129.0,58.0
top_element,328.0,177.0,328.0,185.0,180.0
top_element_info,"{'id': 328, 'points': 14}","{'id': 177, 'points': 20}","{'id': 328, 'points': 17}","{'id': 185, 'points': 15}","{'id': 180, 'points': 16}"
transfers_made,0,13364453,23723836,25930392,13036058
most_captained,351.0,351.0,351.0,351.0,351.0
most_vice_captained,351.0,401.0,328.0,328.0,351.0

In [17]:
events['deadline_time'] = pd.to_datetime(events['deadline_time']).dt.date

In [18]:
#store the last gameweek as a string (i.e. Gameweek_3); for labelling the data exported from this file
last_gameweek = events.loc[events['deadline_time'] < date.today()]['name'].iloc[-1].replace(' ', '_')
last_gameweek_number = events.loc[events['deadline_time'] < date.today()]['id'].iloc[-1]

In [19]:
fixtures.drop(['id', 'code', 'finished', 'finished_provisional', 'minutes', 'provisional_start_time', 'started', 'stats', 'pulse_id'], axis=1, inplace=True)
fixtures.rename(columns={'event': 'Gameweek'}, inplace=True)
fixtures.head()

,Gameweek,kickoff_time,team_a,team_a_score,team_h,team_h_score,team_h_difficulty,team_a_difficulty
0,1,2024-08-16T19:00:00Z,9,0.0,14,1.0,2,3
1,1,2024-08-17T11:30:00Z,12,2.0,10,0.0,4,2
2,1,2024-08-17T14:00:00Z,20,0.0,1,2.0,2,5
3,1,2024-08-17T14:00:00Z,5,3.0,8,0.0,2,3
4,1,2024-08-17T14:00:00Z,17,0.0,15,1.0,2,4

In [20]:
fixtures['kickoff_date'] = fixtures['kickoff_time'].apply(lambda x: x.split('T')[0])
fixtures['kickoff_time'] = fixtures['kickoff_time'].apply(lambda x: x.split('T')[1].replace('Z', ''))
fixtures = fixtures[['Gameweek', 'kickoff_date', 'kickoff_time', 'team_a', 'team_a_score', 'team_h', 'team_h_score', 'team_h_difficulty', 'team_a_difficulty']]

In [21]:
fixtures.head()

,Gameweek,kickoff_date,kickoff_time,team_a,team_a_score,team_h,team_h_score,team_h_difficulty,team_a_difficulty
0,1,2024-08-16,19:00:00,9,0.0,14,1.0,2,3
1,1,2024-08-17,11:30:00,12,2.0,10,0.0,4,2
2,1,2024-08-17,14:00:00,20,0.0,1,2.0,2,5
3,1,2024-08-17,14:00:00,5,3.0,8,0.0,2,3
4,1,2024-08-17,14:00:00,17,0.0,15,1.0,2,4

In [22]:
fixtures['team_a'] = fixtures['team_a'].map(teams.set_index('id').name)
fixtures['team_h'] = fixtures['team_h'].map(teams.set_index('id').name)

In [23]:
fixtures.head()

,Gameweek,kickoff_date,kickoff_time,team_a,team_a_score,team_h,team_h_score,team_h_difficulty,team_a_difficulty
0,1,2024-08-16,19:00:00,Fulham,0.0,Man Utd,1.0,2,3
1,1,2024-08-17,11:30:00,Liverpool,2.0,Ipswich,0.0,4,2
2,1,2024-08-17,14:00:00,Wolves,0.0,Arsenal,2.0,2,5
3,1,2024-08-17,14:00:00,Brighton,3.0,Everton,0.0,2,3
4,1,2024-08-17,14:00:00,Southampton,0.0,Newcastle,1.0,2,4

In [24]:
url_myteam = 'https://fantasy.premierleague.com/api/entry/155692/event/{}/picks/'.format(last_gameweek_number)
r_myteam = requests.get(url_myteam)
json_myteam = r_myteam.json()

In [25]:
my_team = pd.DataFrame(json_myteam['picks'])
my_team['element'] = my_team['element'].map(players.set_index('id').web_name)
my_team.drop('position', axis=1, inplace=True)
my_team.rename(columns={'element': 'Players'}, inplace=True)
my_team

             Players  multiplier  is_captain  is_vice_captain
0          Henderson           1       False            False
1        Pedro Porro           1       False            False
2           Robinson           1       False            False
3   Alexander-Arnold           1       False            False
4            Johnson           1       False            False
5                Eze           1       False            False
6             Souček           1       False            False
7            M.Salah           2        True            False
8            Haaland           1       False             True
9         João Pedro           1       False            False
10     Calvert-Lewin           1       False            False
11        J.Virginia           0       False            False
12         Mykolenko           0       False            False
13           Sangaré           0       False            False
14          Diogo J.           0       False            False

In [26]:
players.columns

Index(['chance_of_playing_next_round', 'chance_of_playing_this_round', 'code',
       'cost_change_event', 'cost_change_event_fall', 'cost_change_start',
       'cost_change_start_fall', 'dreamteam_count', 'element_type', 'ep_next',
       'ep_this', 'event_points', 'first_name', 'form', 'id', 'in_dreamteam',
       'news', 'news_added', 'now_cost', 'photo', 'points_per_game',
       'second_name', 'selected_by_percent', 'special', 'squad_number',
       'status', 'team', 'team_code', 'total_points', 'transfers_in',
       'transfers_in_event', 'transfers_out', 'transfers_out_event',
       'value_form', 'value_season', 'web_name', 'region', 'minutes',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'starts', 'expected_goals', 'expected_assists',
       'expected_goal_involvements', 'expected_goals_conceded',
       'influence_rank', 'influence_rank_type', 'creativity_rank',
       'creativity_rank_type', 'threat_rank', 'threat_rank_type',
       'ict_index_rank', 'ict_index_rank_type',
       'corners_and_indirect_freekicks_order',
       'corners_and_indirect_freekicks_text', 'direct_freekicks_order',
       'direct_freekicks_text', 'penalties_order', 'penalties_text',
       'expected_goals_per_90', 'saves_per_90', 'expected_assists_per_90',
       'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90',
       'goals_conceded_per_90', 'now_cost_rank', 'now_cost_rank_type',
       'form_rank', 'form_rank_type', 'points_per_game_rank',
       'points_per_game_rank_type', 'selected_rank', 'selected_rank_type',
       'starts_per_90', 'clean_sheets_per_90'],
      dtype='object')

In [27]:
player_types.head()

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_select,squad_max_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,None,None,1,1,True,[12],70
1,2,Defenders,DEF,Defender,DEF,5,None,None,3,5,False,[],215
2,3,Midfielders,MID,Midfielder,MID,5,None,None,2,5,False,[],303
3,4,Forwards,FWD,Forward,FWD,3,None,None,1,3,False,[],73

In [28]:
players['position'] = players.element_type.map(player_types.set_index('id').singular_name)
players.head()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,position
0,0.0,0.0,438098,0,0,-1,1,0,3,0.0,...,86,639,291,645,295,605,266,0.0,0.0,Midfielder
1,100.0,100.0,205651,0,0,-2,2,0,4,1.8,...,16,364,39,413,45,201,37,0.0,0.0,Forward
2,NaN,NaN,226597,1,-1,1,-1,1,2,9.5,...,3,6,1,5,1,16,5,1.0,0.6,Defender
3,NaN,NaN,219847,0,0,1,-1,1,4,5.5,...,4,58,11,26,7,19,6,1.0,0.6,Forward
4,0.0,0.0,463748,0,0,0,0,0,1,0.0,...,65,413,48,456,53,527,65,0.0,0.0,Goalkeeper

In [29]:
players['team'] = players.team.map(teams.set_index('id').name)
players.head()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,position
0,0.0,0.0,438098,0,0,-1,1,0,3,0.0,...,86,639,291,645,295,605,266,0.0,0.0,Midfielder
1,100.0,100.0,205651,0,0,-2,2,0,4,1.8,...,16,364,39,413,45,201,37,0.0,0.0,Forward
2,NaN,NaN,226597,1,-1,1,-1,1,2,9.5,...,3,6,1,5,1,16,5,1.0,0.6,Defender
3,NaN,NaN,219847,0,0,1,-1,1,4,5.5,...,4,58,11,26,7,19,6,1.0,0.6,Forward
4,0.0,0.0,463748,0,0,0,0,0,1,0.0,...,65,413,48,456,53,527,65,0.0,0.0,Goalkeeper

In [30]:
players = players.drop(columns = ['id', 'first_name', 'second_name', 'chance_of_playing_next_round', 'chance_of_playing_this_round', 'code', 'cost_change_event', 'cost_change_event_fall', 
                                  'cost_change_start', 'cost_change_start_fall', 'dreamteam_count', 'element_type', 'ep_next', 'ep_this',
                                  'form', 'in_dreamteam', 'news', 'news_added', 'photo', 'special', 'squad_number', 'team_code', 'transfers_in',
                                  'transfers_in_event', 'transfers_out', 'transfers_out_event', 'value_form', 'value_season', 'influence_rank',
                                  'influence_rank_type', 'creativity_rank', 'creativity_rank_type', 'threat_rank', 'threat_rank_type', 'ict_index_rank',
                                  'ict_index_rank_type', 'corners_and_indirect_freekicks_text', 'direct_freekicks_text', 'penalties_text', 'now_cost_rank', 
                                  'now_cost_rank_type', 'form_rank', 'form_rank_type', 'points_per_game_rank', 'points_per_game_rank_type', 'selected_rank', 
                                  'selected_rank_type'])

In [31]:
players.columns

Index(['event_points', 'now_cost', 'points_per_game', 'selected_by_percent',
       'status', 'team', 'total_points', 'web_name', 'region', 'minutes',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'starts', 'expected_goals', 'expected_assists',
       'expected_goal_involvements', 'expected_goals_conceded',
       'corners_and_indirect_freekicks_order', 'direct_freekicks_order',
       'penalties_order', 'expected_goals_per_90', 'saves_per_90',
       'expected_assists_per_90', 'expected_goal_involvements_per_90',
       'expected_goals_conceded_per_90', 'goals_conceded_per_90',
       'starts_per_90', 'clean_sheets_per_90', 'position'],
      dtype='object')

In [32]:
players.head().T

,0,1,2,3,4
event_points,0,0,7,2,0
now_cost,54,68,61,81,40
points_per_game,0.0,0.3,7.2,5.2,0.0
selected_by_percent,0.0,0.9,21.3,17.7,0.0
status,u,a,a,a,u
team,Arsenal,Arsenal,Arsenal,Arsenal,Arsenal
total_points,0,1,36,26,0
web_name,Fábio Vieira,G.Jesus,Gabriel,Havertz,Hein
region,NaN,30.0,30.0,80.0,NaN
minutes,0,18,450,450,0
goals_scored,0,0,2,2,0
assists,0,0,0,1,0
clean_sheets,0,0,3,3,0
goals_conceded,0,1,3,3,0
own_goals,0,0,0,0,0
penalties_saved,0,0,0,0,0
penalties_missed,0,0,0,0,0
yellow_cards,0,2,1,0,0
red_cards,0,0,0,0,0
saves,0,0,0,0,0
bonus,0,0,4,5,0
bps,0,5,119,97,0
influence,0.0,10.2,170.6,136.0,0.0
creativity,0.0,0.8,25.6,60.4,0.0
threat,0.0,0.0,92.0,144.0,0.0
ict_index,0.0,1.1,28.8,34.0,0.0
starts,0,0,5,5,0
expected_goals,0.00,0.00,1.00,1.63,0.00
expected_assists,0.00,0.00,0.06,0.12,0.00
expected_goal_involvements,0.00,0.00,1.06,1.75,0.00
expected_goals_conceded,0.00,0.97,6.48,6.48,0.00
corners_and_indirect_freekicks_order,NaN,NaN,NaN,NaN,NaN
direct_freekicks_order,NaN,NaN,NaN,NaN,NaN
penalties_order,NaN,NaN,NaN,3.0,NaN
expected_goals_per_90,0.0,0.0,0.2,0.33,0.0
saves_per_90,0.0,0.0,0.0,0.0,0.0
expected_assists_per_90,0.0,0.0,0.01,0.02,0.0
expected_goal_involvements_per_90,0.0,0.0,0.21,0.35,0.0
expected_goals_conceded_per_90,0.0,4.85,1.3,1.3,0.0
goals_conceded_per_90,0.0,5.0,0.6,0.6,0.0
starts_per_90,0.0,0.0,1.0,1.0,0.0
clean_sheets_per_90,0.0,0.0,0.6,0.6,0.0
position,Midfielder,Forward,Defender,Forward,Goalkeeper

In [33]:
players.to_excel('data/players_{}.xlsx'.format(last_gameweek), index=False)
fixtures.to_excel('data/fixtures.xlsx', index=False)
my_team.to_excel('data/my_team_{}.xlsx'.format(last_gameweek), index=False)